Beginner part 3 crud
saveroz/saveroz-golang-training-beginner pull request #3
Opened 2021-06-09 03:40 UTC by saveroz

2021-06-14 02:30 UTC, owenyuwono requested changes

2021-06-14 02:30 UTC, owenyuwono commented on internal/postgres/paymentcode_test.go
> +	. "github.com/onsi/gomega"
https://github.com/golang/go/wiki/CodeReviewComments#import-dot

> Except for this one case, do not use import

2021-06-14 02:30 UTC, owenyuwono commented on internal/postgres/migrations/migrate.go
> +package migrate
> Another convention is that the package name is the base name of its source directory; the package in src/encoding/base64 is imported as "encoding/base64" but has name base64, not encoding_base64 and not encodingBase64

https://golang.org/doc/effective_go#package-names

2021-06-14 02:30 UTC, owenyuwono commented on internal/postgres/paymentcode_test.go
> +			It("should create payment code successfully", func ()  {
why do we want to use this?
we are using Golang, not node.js. So if we are still doing it "the node.js way" maybe it's better to go back to node.js instead of Golang

2021-06-14 02:30 UTC, owenyuwono commented on internal/rest/paymentcode_test.go
> +})
this long file could be shorter with Go's table testing instead of node.js structure

2021-06-14 05:52 UTC, saveroz commented on internal/postgres/paymentcode_test.go
> +			It("should create payment code successfully", func ()  {
i think it's more accurate to say "BDD style" not "nodejs way".

Okay there are few reason why i'm using BDD style for the unit test 

1. It's make my unit test more intuitive and descriptive.
2. Based on my experience in with golang's testing package in cashpay new architecture repo. it's harder to debug when some unit tests are fails.
3. I want to learn other golang testing framework. since the current new architecture uses all golang's testing package.
4. I don't know it's not recommended to use BDD style in golang.
5. iirc there's no restriction to use BDD style from our golang training session. cmiiw 

anyway thanks for the review mate.

2021-06-14 07:31 UTC, owenyuwono commented on internal/postgres/paymentcode_test.go
> +			It("should create payment code successfully", func ()  {
1. ginkgo was built for go 1.7 and lower, when golang's test package was very bare and hard to use so it's understandable to use it before 1.7, but since then, Golang's test package has improved by miles, and it has become the de facto standard of testing in Golang.
2. ginkgo is not capable of concurrent test
3. using ginkgo also will make you do extra steps when creating benchmark tests

> It's make my unit test more intuitive and descriptive
> Based on my experience in with golang's testing package in cashpay new architecture repo. it's harder to debug when some unit tests are fails

can you elaborate on these points? why using golang standard lib is not intuitive and/or descriptive? also are you sure it's harder to debug because of the framework, or is it because of the implementation?

> iirc there's no restriction to use BDD style from our golang training session. cmiiw

yeah my fault, there isn't because I didn't expect it would be implemented here.

> I don't know it's not recommended to use BDD style in golang.

Honestly I also don't know if it is or isn't, but based on my experience, nobody actually does it. Nobody in the Golang community in reddit, or gopher slack channel, in Tokopedia, or while I was being interviewed at a lot of other companies (gojek, shopee, ruangguru, etc.). Only in Xendit, first time I saw it in RO, and I would like to change it.

Contrary to js development which I experienced it as a frontend before, usually Golang Developers keeps their dependencies minimal, people here would say to me "why reinvent the wheel if somebody already made it in the wild", "Reinventing the wheel" principle is a good principle and I agree with the meaning of it but please take a look at this article https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code/ it was shared by someone in randev. Other than that article I would also ask back "why would that somebody that made the library in the wild reinvent the wheel when it's all already there in the Golang's standard library"

Anyway, forgive my tone, but I usually get agitated when someone tries to bring js philosophy to Golang. it's a different language, move on. Also I'm not requiring you to change it, I just want you to understand that Golang and Node.js is different

2021-06-21 08:32 UTC, saveroz commented on internal/postgres/paymentcode_test.go
> +	. "github.com/onsi/gomega"
updated this one

2021-06-21 08:32 UTC, saveroz commented on internal/postgres/migrations/migrate.go
> +package migrate
okay i've changed the names

2021-06-21 08:33 UTC, saveroz commented on internal/rest/paymentcode_test.go
> +})
i have state few reason why i'm using BDD style in above

2021-06-21 08:44 UTC, khasburrahman commented on internal/postgres/paymentcode_test.go
> +			It("should create payment code successfully", func ()  {
Hi Just to chime in this one.

Reason previously it is introduced to RO is: 
- to make migrating from JS to Golang more easier for JS devs  
  there was no intention to make this as standards, just people preference 🙏

2021-06-21 08:51 UTC, khasburrahman commented
Could you please help to add more deps to the endpoint? 
- To practice unit testing & mocking with multiple dependencies [context](https://xendit.slack.com/archives/C01U4KF0A92/p1621914666005600)

2021-06-21 08:57 UTC, haveiss commented on internal/postgres/paymentcode_test.go
> +var BeNil = gomega.BeNil
instead of declare it one by one you can import it using .
```
import (
        // other 
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)
```

2021-06-21 08:57 UTC, haveiss commented on internal/rest/paymentcode_test.go
> +var Equal = gomega.Equal
see my comment above

2021-06-21 09:05 UTC, haveiss commented on mocks/IPaymentService.go
> +        gomock "github.com/golang/mock/gomock"
no need alias import for same name

2021-06-21 09:05 UTC, haveiss commented on mocks/IPaymentCodeRepository.go
> +        gomock "github.com/golang/mock/gomock"
no need alias import for same name

2021-06-21 10:42 UTC, saveroz commented on internal/postgres/paymentcode_test.go
> +var BeNil = gomega.BeNil
so yeah i previously use this one but owen said it's not recommended to use dot import https://github.com/saveroz/saveroz-golang-training-beginner/pull/3#discussion_r650617644

2021-06-21 10:43 UTC, saveroz commented on internal/rest/paymentcode_test.go
> +var Equal = gomega.Equal
same as this one https://github.com/saveroz/saveroz-golang-training-beginner/pull/3#discussion_r655268648

2021-06-22 00:32 UTC, saveroz commented on internal/postgres/paymentcode_test.go
> +			It("should create payment code successfully", func ()  {
> can you elaborate on these points? why using golang standard lib is not intuitive and/or descriptive?
okay let give you comparison when unit test are fails in ginkgo and golang standard lib

1. Golang testing l
![golang standard lib](https://user-images.githubusercontent.com/36983520/122844327-a4fc8880-d32b-11eb-863f-6ebb92f1ea10.png)

2. Ginkgo 
![ginkgo](https://user-images.githubusercontent.com/36983520/122844362-b776c200-d32b-11eb-8f6b-47d53bcc92b0.png)
ib

you can see above comparison when one of the unit test is fails ginkgo only shows which unit test is fails and didn't show others testings which passed.

2021-06-22 04:20 UTC, owenyuwono commented on mocks/IPaymentService.go
> +        gomock "github.com/golang/mock/gomock"
this one is generated by mockery @haveiss

2021-06-22 04:21 UTC, owenyuwono commented on internal/postgres/paymentcode_test.go
> +var BeNil = gomega.BeNil
why not just use `ginkgo.Describe()` in the tests?

2021-06-22 06:16 UTC, saveroz commented on internal/postgres/paymentcode_test.go
> +var BeNil = gomega.BeNil
okay updated

2021-06-22 06:16 UTC, saveroz commented on internal/rest/paymentcode_test.go
> +var Equal = gomega.Equal
updated to use ginkgo.Describe like owen suggested

2021-06-22 08:38 UTC, owenyuwono commented on internal/postgres/paymentcode_test.go
> +			It("should create payment code successfully", func ()  {
<img width="991" alt="Screen Shot 2021-06-22 at 15 35 20" src="https://user-images.githubusercontent.com/22276905/122892336-7f916e00-d36f-11eb-98be-690493729974.png">

how about this, is this not easy to identify?

<img width="991" alt="Screen Shot 2021-06-22 at 15 36 58" src="https://user-images.githubusercontent.com/22276905/122892567-b2d3fd00-d36f-11eb-8c7c-7030a4c20389.png">

or this, if you want to show only the failed ones

and the [no test files] also helps us to point out which package that does not have tests yet, is it irrelevant to you?

2021-06-25 08:19 UTC, saveroz commented
> Could you please help to add more deps to the endpoint?
> 
> * To practice unit testing & mocking with multiple dependencies [context](https://xendit.slack.com/archives/C01U4KF0A92/p1621914666005600)

I've added the redis dependency also redis integration test.

2021-06-25 08:22 UTC, saveroz commented on internal/postgres/paymentcode_test.go
> +			It("should create payment code successfully", func ()  {
okayy your point taken. i'll use golang testing lib in the future. 
thanks for the discussion.

2021-06-29 03:52 UTC, khasburrahman approved these changes

2021-06-29 04:01 UTC, merged